### 회원가입
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password123"
}

### 로그인
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password123"
}

### 디바이스 등록
POST http://localhost:8080/devices
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QHRlc3QuY29tIiwiaWF0IjoxNzc0MTYxOTAwLCJleHAiOjE3NzQxNjU1MDB9.H5vh1GX-AUWkyIhThd_DMMbBUAF_R2h5Tuo82H6PvAUGQiV7QVjsEdm_LHUAURxt

{
  "name": "온도센서1",
  "type": "TEMPERATURE",
  "location": "공장1층",
  "thresholdValue": 80.0
}

### 내 디바이스 목록
GET http://localhost:8080/devices
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QHRlc3QuY29tIiwiaWF0IjoxNzc0MTYxOTAwLCJleHAiOjE3NzQxNjU1MDB9.H5vh1GX-AUWkyIhThd_DMMbBUAF_R2h5Tuo82H6PvAUGQiV7QVjsEdm_LHUAURxt

### 디바이스 수정
PUT http://localhost:8080/devices/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QHRlc3QuY29tIiwiaWF0IjoxNzc0MTYxOTAwLCJleHAiOjE3NzQxNjU1MDB9.H5vh1GX-AUWkyIhThd_DMMbBUAF_R2h5Tuo82H6PvAUGQiV7QVjsEdm_LHUAURxt

{
  "name": "온도센서1-수정",
  "type": "TEMPERATURE",
  "location": "공장2층",
  "thresholdValue": 90.0
}

### 디바이스 삭제
DELETE http://localhost:8080/devices/1
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QHRlc3QuY29tIiwiaWF0IjoxNzc0MTYxOTAwLCJleHAiOjE3NzQxNjU1MDB9.H5vh1GX-AUWkyIhThd_DMMbBUAF_R2h5Tuo82H6PvAUGQiV7QVjsEdm_LHUAURxt


### 센서 데이터 전송
POST http://localhost:8080/sensor-data
Content-Type: application/json

{
  "deviceId": 5,
  "value": 81.2
}