spring:
  datasource:
    url: jdbc:postgresql:///iot_sensor_db?cloudSqlInstance=project-f4d2acb6-c4a9-4f38-9be:asia-northeast3:iot-db-instance&socketFactory=com.google.cloud.sql.postgres.SocketFactory
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  cloud:
    gcp:
      sql:
        database-name: iot_sensor_db
        instance-connection-name: project-f4d2acb6-c4a9-4f38-9be:asia-northeast3:iot-db-instance
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

jwt:
  secret-key: ${JWT_SECRET}
  expiration: 3600000

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
  api-docs:
    path: /api-docs