spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/iot_sensor_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret-key: ${JWT_SECRET:iot-sensor-platform-jwt-secret-key-must-be-at-least-32}
  expiration: 3600000