CREATE TABLE factories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz(6),
    description varchar(255),
    name varchar(255) NOT NULL,
    updated_at timestamptz(6)
);

CREATE TABLE zones (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz(6),
    description varchar(255),
    name varchar(255) NOT NULL,
    updated_at timestamptz(6),
    factory_id bigint NOT NULL,
    CONSTRAINT fk_zones_factory FOREIGN KEY (factory_id) REFERENCES factories (id)
);

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz(6),
    email varchar(255),
    employee_id varchar(255) NOT NULL,
    name varchar(255) NOT NULL,
    password varchar(255),
    role varchar(255) NOT NULL,
    status varchar(255) NOT NULL,
    updated_at timestamptz(6),
    factory_id bigint,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT uk_users_employee_id UNIQUE (employee_id),
    CONSTRAINT ck_users_role CHECK (role IN ('SYSTEM_ADMIN', 'FACTORY_ADMIN', 'MEMBER', 'VIEWER')),
    CONSTRAINT ck_users_status CHECK (status IN ('PENDING', 'ACTIVE', 'REJECTED')),
    CONSTRAINT fk_users_factory FOREIGN KEY (factory_id) REFERENCES factories (id)
);

CREATE TABLE zone_users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz(6),
    user_id bigint NOT NULL,
    zone_id bigint NOT NULL,
    CONSTRAINT uk_zone_users_zone_user UNIQUE (zone_id, user_id),
    CONSTRAINT fk_zone_users_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_zone_users_zone FOREIGN KEY (zone_id) REFERENCES zones (id)
);

CREATE TABLE device (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz(6),
    expected_interval_seconds integer,
    location varchar(255),
    name varchar(255),
    threshold_value double precision,
    type varchar(255),
    updated_at timestamptz(6),
    zone_id bigint,
    CONSTRAINT ck_device_type CHECK (
        type IN ('TEMPERATURE', 'PRESSURE', 'CURRENT', 'POWER', 'ACCELERATION')
    ),
    CONSTRAINT fk_device_zone FOREIGN KEY (zone_id) REFERENCES zones (id)
);

CREATE TABLE device_status (
    device_id bigint PRIMARY KEY,
    in_alarm boolean NOT NULL,
    last_alert_at timestamptz(6),
    last_seen_at timestamptz(6),
    CONSTRAINT fk_device_status_device FOREIGN KEY (device_id) REFERENCES device (id)
);

CREATE TABLE sensor_data (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recorded_at timestamptz(6),
    value double precision,
    device_id bigint,
    CONSTRAINT fk_sensor_data_device FOREIGN KEY (device_id) REFERENCES device (id)
);

CREATE INDEX idx_sensor_device_recorded ON sensor_data (device_id, recorded_at);

CREATE TABLE alert (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz(6),
    evidence varchar(255),
    message varchar(255),
    recommendation varchar(255),
    sensor_value double precision,
    severity varchar(255),
    threshold_value double precision,
    updated_at timestamptz(6),
    device_id bigint,
    CONSTRAINT ck_alert_severity CHECK (severity IN ('INFO', 'WARNING', 'CRITICAL')),
    CONSTRAINT fk_alert_device FOREIGN KEY (device_id) REFERENCES device (id)
);

CREATE TABLE failed_reading (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz(6),
    device_id bigint,
    reason varchar(255),
    value double precision
);

CREATE TABLE refresh_tokens (
    employee_id varchar(255) PRIMARY KEY,
    expires_at timestamptz(6) NOT NULL,
    token varchar(255) NOT NULL
);
