-- 수신 모델을 "채널=Device" 에서 "물리 Device ─ SensorChannel ─ MeasurementBatch ─ SensorReading"
-- 정규화 모델로 전환한다. 같은 관측 시점(batch)의 여러 채널 값을 한 묶음으로 보존한다.
--
-- 이 branch 의 V2 는 아직 어디에도 배포·push 되지 않았고 이관 수혜자가 없으므로,
-- 누적 DDL 을 새로 쌓지 않고 V2 자체를 재작성한다(공개 데모 토폴로지는 V3 로 분리).
-- V1 은 checksum 고정을 위해 수정하지 않는다.

-- 1) device: 설정만 남긴다. 측정 종류·임계값은 채널 경계로 이동하므로 제거하고,
--    물리 노드를 가리키는 안정적 식별자 code(UK)를 추가한다.
ALTER TABLE device DROP CONSTRAINT ck_device_type;
ALTER TABLE device DROP COLUMN type;
ALTER TABLE device DROP COLUMN threshold_value;
ALTER TABLE device ADD COLUMN code varchar(255) NOT NULL;
ALTER TABLE device ADD CONSTRAINT uk_device_code UNIQUE (code);

-- 2) device_status: 알람 상태는 채널 경계(channel_status)로 이동한다. 노드 freshness(last_seen_at)만 남긴다.
ALTER TABLE device_status DROP COLUMN in_alarm;
ALTER TABLE device_status DROP COLUMN last_alert_at;

-- 3) sensor_channel: 물리 Device 아래의 측정 채널. 임계값·임계 방향을 채널이 가진다.
CREATE TABLE sensor_channel (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz(6),
    updated_at timestamptz(6),
    code varchar(255) NOT NULL,
    unit varchar(255),
    quantity_kind varchar(255),
    threshold_value double precision,
    threshold_direction varchar(255),
    device_id bigint NOT NULL,
    CONSTRAINT uk_sensor_channel_device_code UNIQUE (device_id, code),
    CONSTRAINT ck_sensor_channel_direction CHECK (threshold_direction IN ('ABOVE', 'BELOW')),
    CONSTRAINT fk_sensor_channel_device FOREIGN KEY (device_id) REFERENCES device (id)
);

-- 4) measurement_batch: 한 payload/원본 한 행의 관측 묶음. 같은 batch 의 채널은 같은 observed_at 을 공유한다.
--    received_at 은 감사 필드가 아니라 서비스가 주입 Clock 으로 세팅한다(@CreatedDate 아님).
CREATE TABLE measurement_batch (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    observed_at timestamptz(6),
    received_at timestamptz(6),
    source_seq bigint,
    device_id bigint NOT NULL,
    CONSTRAINT fk_measurement_batch_device FOREIGN KEY (device_id) REFERENCES device (id)
);
CREATE INDEX idx_measurement_batch_device_observed ON measurement_batch (device_id, observed_at);

-- 5) sensor_reading: batch × channel 교차의 단일 값. 감사 컬럼 없음.
CREATE TABLE sensor_reading (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value double precision,
    batch_id bigint NOT NULL,
    channel_id bigint NOT NULL,
    CONSTRAINT uk_sensor_reading_batch_channel UNIQUE (batch_id, channel_id),
    CONSTRAINT fk_sensor_reading_batch FOREIGN KEY (batch_id) REFERENCES measurement_batch (id),
    CONSTRAINT fk_sensor_reading_channel FOREIGN KEY (channel_id) REFERENCES sensor_channel (id)
);
CREATE INDEX idx_sensor_reading_channel ON sensor_reading (channel_id);

-- 6) channel_status: 채널의 알람 상태(엣지 트리거 쿨다운). DeviceStatus 의 @MapsId 공유 PK 패턴을 복제한다.
CREATE TABLE channel_status (
    channel_id bigint PRIMARY KEY,
    in_alarm boolean NOT NULL,
    last_alert_at timestamptz(6),
    CONSTRAINT fk_channel_status_channel FOREIGN KEY (channel_id) REFERENCES sensor_channel (id)
);

-- 7) alert: 어떤 batch·channel 에서 났는지 참조를 추가한다.
--    device_id 는 nullable 유지 — 임계 alert 는 셋 다, freshness alert 는 device_id 만 세팅한다.
ALTER TABLE alert ADD COLUMN channel_id bigint;
ALTER TABLE alert ADD COLUMN batch_id bigint;
ALTER TABLE alert ADD CONSTRAINT fk_alert_channel FOREIGN KEY (channel_id) REFERENCES sensor_channel (id);
ALTER TABLE alert ADD CONSTRAINT fk_alert_batch FOREIGN KEY (batch_id) REFERENCES measurement_batch (id);

-- 8) failed_reading: 새 API 는 문자열 식별자(deviceCode/channelCode)로 실패를 기록한다.
ALTER TABLE failed_reading ADD COLUMN device_code varchar(255);
ALTER TABLE failed_reading ADD COLUMN channel_code varchar(255);

-- 9) sensor_data: scalar 텔레메트리 테이블 제거(호환 레이어 없음, 미배포·외부 소비자 0명). 인덱스는 테이블과 함께 삭제된다.
DROP TABLE sensor_data;
