CREATE TABLE factory_operating_calendar (
    factory_id bigint PRIMARY KEY,
    timezone_id varchar(64) NOT NULL,
    resume_grace_seconds integer NOT NULL DEFAULT 300,
    revision bigint NOT NULL DEFAULT 0,
    created_at timestamptz(6) NOT NULL,
    updated_at timestamptz(6) NOT NULL,
    CONSTRAINT fk_factory_operating_calendar_factory
        FOREIGN KEY (factory_id) REFERENCES factories (id) ON DELETE CASCADE,
    CONSTRAINT ck_factory_operating_calendar_grace
        CHECK (resume_grace_seconds BETWEEN 0 AND 86400),
    CONSTRAINT ck_factory_operating_calendar_revision
        CHECK (revision >= 0)
);

CREATE TABLE factory_weekly_interval (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    factory_id bigint NOT NULL,
    iso_day smallint NOT NULL,
    start_minute smallint NOT NULL,
    end_minute smallint NOT NULL,
    CONSTRAINT fk_factory_weekly_interval_calendar
        FOREIGN KEY (factory_id) REFERENCES factory_operating_calendar (factory_id) ON DELETE CASCADE,
    CONSTRAINT ck_factory_weekly_interval_day CHECK (iso_day BETWEEN 1 AND 7),
    CONSTRAINT ck_factory_weekly_interval_minutes
        CHECK (start_minute BETWEEN 0 AND 1439 AND end_minute BETWEEN 1 AND 1440 AND start_minute < end_minute),
    CONSTRAINT uk_factory_weekly_interval UNIQUE (factory_id, iso_day, start_minute, end_minute)
);

CREATE INDEX idx_factory_weekly_interval_factory_day
    ON factory_weekly_interval (factory_id, iso_day);

CREATE TABLE factory_date_override (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    factory_id bigint NOT NULL,
    local_date date NOT NULL,
    kind varchar(16) NOT NULL,
    CONSTRAINT fk_factory_date_override_calendar
        FOREIGN KEY (factory_id) REFERENCES factory_operating_calendar (factory_id) ON DELETE CASCADE,
    CONSTRAINT ck_factory_date_override_kind CHECK (kind IN ('CLOSED', 'OPEN')),
    CONSTRAINT uk_factory_date_override UNIQUE (factory_id, local_date)
);

CREATE INDEX idx_factory_date_override_factory_date
    ON factory_date_override (factory_id, local_date);

CREATE TABLE factory_date_override_interval (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    override_id bigint NOT NULL,
    start_minute smallint NOT NULL,
    end_minute smallint NOT NULL,
    CONSTRAINT fk_factory_date_override_interval_override
        FOREIGN KEY (override_id) REFERENCES factory_date_override (id) ON DELETE CASCADE,
    CONSTRAINT ck_factory_date_override_interval_minutes
        CHECK (start_minute BETWEEN 0 AND 1439 AND end_minute BETWEEN 1 AND 1440 AND start_minute < end_minute),
    CONSTRAINT uk_factory_date_override_interval UNIQUE (override_id, start_minute, end_minute)
);

CREATE INDEX idx_factory_date_override_interval_override
    ON factory_date_override_interval (override_id);

-- 기존 공장은 우선 24시간 감시로 backfill해 설정 누락이 알림을 숨기지 않게 한다.
INSERT INTO factory_operating_calendar (
    factory_id, timezone_id, resume_grace_seconds, revision, created_at, updated_at
)
SELECT id, 'Asia/Seoul', 300, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM factories;

INSERT INTO factory_weekly_interval (factory_id, iso_day, start_minute, end_minute)
SELECT f.id, day.iso_day, 0, 1440
FROM factories f
CROSS JOIN (VALUES (1), (2), (3), (4), (5), (6), (7)) AS day(iso_day);

-- V3 공개 데모 두 공장은 simulator-live 기본값과 같은 평일 08:00~18:00으로 시작한다.
DELETE FROM factory_weekly_interval
WHERE factory_id IN (SELECT id FROM factories WHERE name IN ('엔진시험동', '가공동'));

INSERT INTO factory_weekly_interval (factory_id, iso_day, start_minute, end_minute)
SELECT f.id, day.iso_day, 480, 1080
FROM factories f
CROSS JOIN (VALUES (1), (2), (3), (4), (5)) AS day(iso_day)
WHERE f.name IN ('엔진시험동', '가공동');
