name: Iot Sensor Platform CI
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: services/backend
      - name: Build with Gradle
        run: ./gradlew build
        working-directory: services/backend
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install simulator dependencies
        run: pip install -r requirements.txt
        working-directory: services/simulator
      - name: Test simulator
        run: python -m unittest -v test_simulator.py
        working-directory: services/simulator
